name: maresto
description: "An App For Getting Restaurant Information Detail of"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  loading_animation_widget: ^1.3.0
  flutter_launcher_icons: ^0.14.2
  sqflite: ^2.4.1
  shared_preferences: ^2.3.5
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.0.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000
  test: ^1.25.8
  mocktail: ^1.0.4
  integration_test_preview: ^0.1.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logoapps.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/logo/logoapps.png
